darkmode: false
development: false
homedir: "/home/{{ item.name }}"

# Follows homelab package list:
# https://git.krislamo.org/kris/homelab/src/branch/main/roles/base/defaults/main.yml#L6
homelab_packages:
  - apache2-utils
  - cryptsetup
  - curl
  - dnsutils
  - hashdeep
  - htop
  - jq
  - kpartx
  - ncdu
  - rsync
  - screen
  - strace
  - tree
  - vim
  - wget

manage_gui: false
packages:
  - "{{ homelab_packages }}"
