- name: Install KDE
  ansible.builtin.apt:
    name: kde-standard
    state: present
    update_cache: true

- name: Create autostart-scripts directory
  ansible.builtin.file:
    path: "{{ homedir }}/.config/autostart-scripts/"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ users }}"
  when: manage_gui

- name: Enable KDE dark theme
  ansible.builtin.copy:
    dest: "{{ homedir }}/.config/autostart-scripts/darkmode.sh"
    mode: a+x
    content: |
      #!/bin/bash
      if ! grep -q "ColorScheme=BreezeDark" ~/.config/kdeglobals; then
        lookandfeeltool -a $(lookandfeeltool --list | grep dark)
      fi
  loop: "{{ users }}"
  when: manage_gui and darkmode

- name: Install sqlite3
  ansible.builtin.apt:
    name: sqlite3
    state: present
  when: manage_gui and favorites is defined or pinned is defined

- name: Change favorites menu
  ansible.builtin.template:
    src: favorites.sh.j2
    dest: "{{ homedir }}/.config/autostart-scripts/favorites.sh"
    mode: a+x
  loop: "{{ users }}"
  when: manage_gui and favorites is defined

- name: Change task manager pinned apps
  ansible.builtin.template:
    src: pinnedapps.sh.j2
    dest: "{{ homedir }}/.config/autostart-scripts/pinnedapps.sh"
    mode: a+x
  loop: "{{ users }}"
  when: manage_gui and pinned is defined
