- name: Install KDE
  apt:
    name: kde-standard
    state: present
    update_cache: true

- name: Create autostart-scripts directory
  file:
    path: "/home/{{ item.name }}/.config/autostart-scripts/"
    state: directory
  loop: "{{ users }}"

- name: Enable KDE dark theme
  copy:
    dest: "/home/{{ item.name }}/.config/autostart-scripts/darkmode.sh"
    mode: a+x
    content: |
      #!/bin/bash
      if ! grep -q "ColorScheme=BreezeDark" ~/.config/kdeglobals; then
        lookandfeeltool -a $(lookandfeeltool --list | grep dark)
      fi
  loop: "{{ users }}"

- name: Install packages
  apt:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: Install sqlite3
  apt:
    name: sqlite3
    state: present

- name: Change favorites menu
  template:
    src: favorites.sh.j2
    dest: "/home/{{ item.name }}/.config/autostart-scripts/favorites.sh"
    mode: a+x
  loop: "{{ users }}"
  tags: debug
