- name: Install KDE
  ansible.builtin.apt:
    name: kde-standard
    state: present
    update_cache: true

- name: Create autostart-scripts directory
  file:
    path: "{{ homedir }}/.config/autostart-scripts/"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"

- name: Enable KDE dark theme
  copy:
    dest: "{{ homedir }}/.config/autostart-scripts/darkmode.sh"
    mode: a+x
    content: |
      #!/bin/bash
      if ! grep -q "ColorScheme=BreezeDark" ~/.config/kdeglobals; then
        lookandfeeltool -a $(lookandfeeltool --list | grep dark)
      fi
  loop: "{{ users }}"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: Install sqlite3
  ansible.builtin.apt:
    name: sqlite3
    state: present

- name: Change favorites menu
  ansible.builtin.template:
    src: favorites.sh.j2
    dest: "{{ homedir }}/.config/autostart-scripts/favorites.sh"
    mode: a+x
  loop: "{{ users }}"

- name: Change task manager pinned apps
  ansible.builtin.template:
    src: pinnedapps.sh.j2
    dest: "{{ homedir }}/.config/autostart-scripts/pinnedapps.sh"
    mode: a+x
  loop: "{{ users }}"

- name: Ensure we have our own comment added to /etc/services
  ansible.builtin.lineinfile:
    path: "{{ homedir }}/.config/autostart-scripts/pinnedapps.sh"
    regexp: '^# port for http'
    insertbefore: '^www.*80/tcp'
    line: '# port for http by default'
  loop: "{{ users }}"
