- name: Import development vagrant tasks
  ansible.builtin.import_tasks: development.yml
  tags: development
  when: development

- name: Import system tasks
  ansible.builtin.import_tasks: system.yml
  tags: system

- name: Import GUI tasks
  ansible.builtin.import_tasks: gui.yml
  tags: gui
